### PR TITLE
Update to use OpenAPI 3 and refactor

### PR DESCRIPTION
**Pull request by justin-tay**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by aklish — APPROVED** [review]

**Review by aklish — CHANGES_REQUESTED** [review]
Local run instructions no longer work:

```
bash-3.2$ java -jar target/elide-heroku-example-1.0.0.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/persistence/EntityManager
        at com.yahoo.elide.standalone.config.ElideStandaloneSettings.<clinit>(ElideStandaloneSettings.java:118)
        at example.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: jakarta.persistence.EntityManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 2 more
```

**Comment by aklish** [comment]
The README is also now incorrect as well.

**Comment by justin-tay** [comment]
> Local run instructions no longer work:
> 
> ```
> bash-3.2$ java -jar target/elide-heroku-example-1.0.0.jar 
> Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/persistence/EntityManager
>         at com.yahoo.elide.standalone.config.ElideStandaloneSettings.<clinit>(ElideStandaloneSettings.java:118)
>         at example.Main.main(Main.java:26)
> Caused by: java.lang.ClassNotFoundException: jakarta.persistence.EntityManager
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>         ... 2 more
> ```

Fixed.

**Comment by justin-tay** [comment]
> The README is also now incorrect as well.

Which part of the README?

**Pull request merged**
